### PR TITLE
[WIP] switch to 2.6 core modules

### PR DESCRIPTION
**Pull request by tobiasleibner**

### CODE REVIEW

**Comment by tobiasleibner** [comment]
The ``test_dd_glued_3d`` test is failing. It is already failing on master for me, but now there are even more tests failing, all due to some ``std::bad_function_call`` exception.

**Comment by tobiasleibner** [comment]
I fixed the additional failing tests in ``test_dd_glued_3d``, but there are also some failures in ``test_dd_glued_2d`` that are not yet marked as STILL_BROKEN. Does anyone care about fixing these tests now or should I just disable them for now?

**Comment by renefritze** [comment]
@ftalbrecht Probably has an interest in fixing those since he's actually using the grid glue code AFAIK.

Other than that: https://github.com/dune-community/dune-xt-grid/tree/compatible_with_2.6_clang-formatted

**Comment by tobiasleibner** [comment]
I included @ftalbrecht's fixes a few days ago and the tests were fixed for me locally. There is still some error on Travis, but I think that error should be easy to fix. I will look into it.

**Comment by tobiasleibner** [comment]
We should probably wait till the [push build](https://travis-ci.org/dune-community/dune-xt-grid/builds/463227989?utm_source=github_status&utm_medium=notification) is green, then we can start merging all the ``compatible_with_2.6`` branches. Probably we should update the ``dune-xt-super`` module before (just replacing ``master`` with ``compatible_with_2.6`` there?).

**Comment by renefritze** [comment]
Good idea about the super. I'll do that right now and disable the PR checks.

**Comment by renefritze** [comment]
I've updated the master for dune-xt-super locally, but did not push yet since the push build you linked failed @tobiasleibner.
I have however already disabled the requisite branch protections in the xt modules.

**Comment by tobiasleibner** [comment]
Ok, the remaining errors are with UG Grid:
```
12/82 Test  #38: test_dd_subdomains_cube_2d_ug_2d_0005 ..........................................***Failed    0.74 sec
[==========] Running 18 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 18 tests from CubeProviderTest
[ RUN      ] CubeProviderTest.setup_works
ERROR in InitCurrMG: opening more than one MG is not allowed in parallel
```
These tests seem to be disabled in the current master, so should we just disable them again @ftalbrecht, @renefritze ?

**Comment by ftalbrecht** [comment]
The fixes I mentioned should also contain a fix for that (by disabling UG in case mpi was found, UG cannot handle that case atm).
As a side note: with the test fixes, there is no need to stick to the old dune-grid-glue version. Any current version may do, as long as these tests pass...

**Comment by tobiasleibner** [comment]
The problem was that the new version of dune-testtools did  not recognize the ``AND NOT`` in the cmake guard. I fixed the cmake guard now. Hopefully now the tests are fine.

**Pull request merged**
