### PR TITLE
[type_traits] fix extract_iterator

### PR DESCRIPTION
**Pull request by tobiasleibner**

### CODE REVIEW

**Comment by renemilk** [comment]
Could you comment on why this is necessary? It does not seem a complete set of changes to me.

**Comment by tobiasleibner** [comment]
Are you okay with this change, @renemilk? Or should I change/add something?

**Comment by renemilk** [comment]
TBH I don't understand why this change is necessary yet. 
```gridview.begin<c>()``` is actually a defaulted ```gridview.begin<c, All_Partition>()```, correct? Why/where does ```extract_partition_iterator``` even exist? The same default could (and I remember setting it just like that) be used in ```extract_iterator```.

**Comment by renemilk** [comment]
Turns out I somehow overlooked the existing ```extract_partition_iterator``` while upgrading ```extract_iterator```. The reason @tobiasleibner stumbled over my change is that the PeriodicGridView actually has different types for extracted iterators. He wants to check if that's actually necessary and if not, deprecate ```extract_partition_iterator``` with an alias to the new imp.

**Comment by tobiasleibner** [comment]
I now made ``PeriodicGridView`` use the same iterator type in ``Codim`` and ``Codim::Partition`` and deprecated ``extract_partition_iterator``.

**Comment by renemilk** [comment]
Awesome. FYI, we do have a new and improved depraction macro in xt-common ```dune/xt/common/deprecated.hh``` ```DXT_DEPRECATED DXT_DEPRECATED_MSG``` which actually has guaranteed compiler support, extended placement possiblities

**Pull request merged**
