### PR TITLE
Refactor walker functors

### PR DESCRIPTION
**Pull request by ftalbrecht**
See also #27. Since this breaks everything in dune-gdt, I would lie to hold this back for a bit...

### CODE REVIEW

**Comment by renemilk** [comment]
CI is still failing since https://github.com/dune-community/dune-xt-common/pull/58 is a requirement for some of these changes here.

Also ping @ftalbrecht  for https://github.com/dune-community/dune-xt-grid/pull/28/commits/7298a40f4a5e59d67319441c7d9fb16000aac2d3

**Comment by renemilk** [comment]
Turns out 79e3ace isn't actually that simple, @ftalbrecht. See also https://github.com/dune-community/dune-xt-common/pull/60/commits/061f0659377a1fa6e97e8b7ae8424bbb174225c1

**Comment by renemilk** [comment]
Clang does not like my generic lambdas :cry:

**Comment by ftalbrecht** [comment]
Although I do not really get the error... :/

**Comment by renemilk** [comment]
FYI @dune-community/dune-xt-devs , I'm rebasing this on master and will force push later.

**Comment by renemilk** [comment]
It is done.

**Comment by ftalbrecht** [comment]
So, I just pushed what I had lying around. I am quite confident that the `refactor-walker-functors__tmp` is now obsolete. How should we proceed w.r.t. this becoming the new master, @dune-community/dune-xt-devs? I think there are some changes which entered master after the branching that we might want to include. I propose to call this branch `new-msater` and to prepare pull requests against this branch with those changes we want to keep. This also applies for all other prs we still have open ...

**Comment by ftalbrecht** [comment]
I tried to merge master into this branch today, but I am not sure if I resolved all conflicts correctly. In particular

* `dune/xt/grid/test/walker.cc`

could use a second glance. In addition, I do net yet know how to (re)generate

* `dune/xt/grid/test/builder_definitions.cmake`
* `dune/xt/grid/test/compiles_totals.pickle`

Do we already have this documented somewhere?

**Comment by renemilk** [comment]
You need to run ```build_command refresh_test_timings```. And outside of cmake this is not documented.

**Comment by ftalbrecht** [comment]
Closing this in favor of #78

**Pull request closed without merging**
