### PR TITLE
[WIP] Dynamic interfaces

### PR DESCRIPTION
**Pull request by renefritze**
calling ```ninja dynamic_interfaces``` should generate a
new dynamic_interfaces.hh in source. This calls ```python/scripts/generate_dynamic_interfaces.py``` internally which uses the python libclang bindings to traverse the AST of a fake translation unit (```dune/xt/grid/dynamic_interfaces.dummy.cc```), process all classes (+class-templates) that match a given filter (https://github.com/dune-community/dune-xt-grid/blob/f270f1ef497e622dde9ed1ffd3771e1cca36f37f/python/scripts/generate_dynamic_interfaces.py#L37) and give the parsed classes data to a jinja template (https://github.com/dune-community/dune-xt-grid/compare/dynamic_interfaces?expand=1#diff-769487942ae0fb54f868a6a8c56c55d6)
The rendered template is then formatted and (if modified) copied to the source dir.

Todos: 
- the code/template does not do the right thing for calling function templates that have non-deducible template parameters
- write actual virtual interface base class with type holder and stuff
- also generate tests for the dynamic interfaces

I won't be working on this until start of october, if anybody wants to before then.

### CODE REVIEW

**Comment by ftalbrecht** [comment]
Nice!

**Comment by renemilk** [comment]
Imo the best option not to lose this would be for me to rebase on master, make sure the infrastructure stuff still works and merge. Even if it really doesn't yet do what to target was.

**Comment by ftalbrecht** [comment]
If you are willing to invest the work: no objections! Does this target enter the `all` target and do we want it to (I hava a bias towards: we don't want this, but I am unsure).

**Comment by renemilk** [comment]
Definitely not something for 'all' atm, since after the rebase on current master it enters an inf loop :roll_eyes: 
Joking aside, for the example/doc stage this is nothing to consider for 'all'. If we use it in production this would most likely be hooked into cmake reconfigure.

**Comment by tobiasleibner** [comment]
We should close this, we can still keep the branch if we want to do this at some point.

**Pull request closed without merging**
