### PR TITLE
Make shared memory parallel computations work without EXADUNE

### PR DESCRIPTION
**Pull request by tobiasleibner**
Currently, you have to use the EXADUNE dune-grid module if you want to use the TBB shared memory functionality in our ``Walker``. This is quite inconvenient, especially because actually we are only depending on a single file ``dune/grid/utility/partitioning/ranged.hh``. 
This pull request is meant as a basis for discussion and currently just copies that file over to ``dune-xt-grid``, with minor changes to remove the `` dune/grid/utility/entityrange.hh`` include.

### CODE REVIEW

**Comment by ftalbrecht** [comment]
Great Idea! I would propose to additionally detect if exadune is present via preprocessor magic in the beginning. If exadune is there, we include the corresponding file from exadune, else we use the content you copied...

**Comment by ftalbrecht** [comment]
LGTM, apart from the failing tests which are unrelated, at least at first glance?

**Comment by renemilk** [comment]
The error's in testtools itself, so yeah, unrelated.

**Comment by ftalbrecht** [comment]
One thing we forgot: we need to mention a license exception for the copied code. Once in the file and once in license...

**Comment by renemilk** [comment]
Headercheck fails too, @tobiasleibner: 
https://travis-ci.org/dune-community/dune-xt-grid/jobs/193061306#L5325

**Pull request merged**
