### PR TITLE
[WIP] Refactor dd_subdomain tests + add test binning

### PR DESCRIPTION
**Pull request by renemilk**
this makes it easier to discover which tests take so long and are
potentially broken and also may help with compile timeouts on travis

see also #32

### CODE REVIEW

**Comment by renemilk** [comment]
Test binary building is now into timeout, whether I use 1 or 2 cores on travis. So binning is also coming to xt-grid after it's done in xt-functions. Yay.

**Comment by ftalbrecht** [comment]
+1

**Comment by renemilk** [comment]
I'd need the subdomain test to not time out for the binning setup to work, @ftalbrecht .
If cutting short its execution time is not something you can do easily/quickly, I could, for now,  just add an immediate fail at runtime on those, so the compile time would still count towards the binning.

**Comment by renemilk** [comment]
Travis currently fails due to out-of-date super/docker where the XT::Configuration change isn't in yet.

**Pull request merged**
